# Github Action to publish Python package to PyPI on release published and tag push
# This workflow builds and publishes new package versions to PyPI when a version tag is pushed
name: Publish Python Package

# Trigger the workflow on release published and tag push events
# Example tags: v1.0.0, v2.1.3, v0.5.0-beta
on:
    release:
        types: [published]

jobs:
    # Main publish job that builds and publishes the package
    build-and-publish:
        # Use latest Ubuntu runner for building
        runs-on: ubuntu-latest

        # Add permissions needed for trusted publishing
        permissions:
            contents: read
            id-token: write

        steps:
            # Step 1: Checkout out the repository code at the tagged version
            - uses: actions/checkout@v3

            # Step 2: Set up Python environment
            # Using Python 3.10 for building to ensure compatibility
            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                  python-version: "3.10"

            # Step 3: Install build for packaging
            # We only need build since we're using trusted publisher
            - name: Install build
              run: pip install build

            # Step 4: Build package
            # This step builds the source distribution and wheel
            - name: Build package
              run: python -m build

            # Step 5: Publish package to PyPI using trusted publisher
            # This uses OIDC authentication instead of a token
            - name: Publish package to PyPI
              uses: pypa/gh-action-pypi-publish@release/v1
